package de.inovex.recognizefoodwithtflite

val foodNameToKorean: Map<String, String> = mapOf(
    "Bacon" to "베이컨",
    "Peanut butter" to "땅콩버터",
    "Acarajé" to "아카라제",
    "Acorn noodle soup" to "도토리 국수",
    "Acquacotta" to "아쿠아코타",
    "Afelia" to "아펠리아",
    "Afghani burger" to "아프가니 버거",
    "Agedashi dōfu" to "아게다시도후",
    "Aguachile" to "아과칠레",
    "Agwi-jjim" to "아귀찜",
    "Ais kacang" to "아이스 카창",
    "Ajapsandali" to "아잡산달리",
    "Ajoblanco" to "아호블랑코",
    "Akple" to "아크플레",
    "Al pastor" to "알 파스토르",
    "Aligot" to "알리고",
    "Alinazik kebab" to "알리나지크 케밥",
    "Alloco" to "알로코",
    "Almond biscuit" to "아몬드 비스킷",
    "Aloo gobi" to "알루 고비",
    "Aloo paratha" to "알루 파라타",
    "Amala" to "아말라",
    "Amanattō" to "아마낫토",
    "Amandine" to "아만딘",
    "Ambelopoulia" to "암벨로풀리아",
    "Ambrosia" to "앰브로시아",
    "Ambuyat" to "암부얏",
    "American chop suey" to "아메리칸 찹 수이",
    "American fried rice" to "아메리칸 볶음밥",
    "American goulash" to "아메리칸 굴라시",
    "Ammonia cookie" to "암모니아 쿠키",
    "Amok trey" to "아목 트레이",
    "Anadama bread" to "아나다마 브레드",
    "Anarsa" to "아나르사",
    "Andouille" to "안두이",
    "Andouillette" to "앙두예트",
    "Angel food cake" to "엔젤 푸드 케이크",
    "Angel wings" to "엔젤 윙스",
    "Anju" to "안주",
    "Ankimo" to "안키모",
    "Annin tofu" to "안닌도후",
    "Anpan" to "단팥빵",
    "Ants climbing a tree" to "마의상수",
    "Apple cake" to "애플 케이크",
    "Apple crisp" to "애플 크리스프",
    "Apple dumpling" to "애플 덤플링",
    "Apple pie" to "애플파이",
    "Apple strudel" to "애플 슈트루델",
    "Arancini" to "아란치니",
    "Arbroath smokie" to "아브로스 스모키",
    "Arctic roll" to "아크틱 롤",
    "Arisa Pitha" to "아리사 피타",
    "Arizona cheese crisp" to "애리조나 치즈 크리스프",
    "Arrosticini" to "아로스티치니",
    "Arroz a la cubana" to "아로스 아 라 쿠바나",
    "Arroz chaufa" to "아로스 차우파",
    "Arroz con pollo" to "아로스 콘 뽀요",
    "Arròs negre" to "아로스 네그레",
    "Asam pedas" to "아삼 페다스",
    "Ash reshteh" to "아쉬 레스테",
    "Asida" to "아시다",
    "Asinan" to "아시난",
    "Aspic" to "아스픽",
    "Assidat Zgougou" to "아시다트 구구",
    "Attiéké" to "아티에케",
    "Avgolemono" to "아브골레모노",
    "Ayam bakar" to "아얌 바카르",
    "Ayam goreng" to "아얌 고렝",
    "Ayam masak merah" to "아얌 마삭 메라",
    "Azerbaijani pakhlava" to "아제르바이잔 파클라바",
    "Açorda" to "아소르다",
    "BLT" to "BLT 샌드위치",
    "Baba ghanoush" to "바바 가누쉬",
    "Babi panggang" to "바비 팡강",
    "Babka" to "바브카",
    "Bacalhau" to "바칼랴우",
    "Bacalhau com natas" to "바칼랴우 콤 나타스",
    "Bacalhau com todos" to "바칼랴우 콤 토도스",
    "Bacalhau à Brás" to "바칼랴우 아 브라스",
    "Bacalhau à Gomes de Sá" to "바칼랴우 아 고메스 데 사",
    "Bacalhau à Zé do Pipo" to "바칼랴우 아 제 두 피포",
    "Baccalà alla lucana" to "바칼라 알라 루카나",
    "Baeckeoffe" to "배케오페",
    "Baek-kimchi" to "백김치",
    "Bagel dog" to "베이글 도그",
    "Baghali ghatogh" to "바갈리 가토그",
    "Baghrir" to "바그리르",
    "Bagnun" to "바뉸",
    "Baji" to "바지",
    "Bak kut teh" to "바쿠테",
    "Bakarkhani" to "바카르카니",
    "Baked potato" to "구운 감자",
    "Bakewell tart" to "베이크웰 타르트",
    "Bakkwa" to "바콰",
    "Baklava" to "바클라바",
    "Bakso" to "박소",
    "Bakwan" to "박완",
    "Balchão" to "발차오",
    "Balkenbrij" to "발켄브레이",
    "Balushahi" to "발루샤히",
    "Bambalouni" to "밤발루니",
    "Bamischijf" to "바미스히프",
    "Banana pudding" to "바나나 푸딩",
    "Banana split" to "바나나 스플릿",
    "Bananas Foster" to "바나나 포스터",
    "Banga" to "방가",
    "Banitsa" to "바니차",
    "Banmian" to "반미안",
    "Banoffee pie" to "바노피 파이",
    "Baodu" to "바오두",
    "Baozi" to "바오쯔",
    "Bara brith" to "바라 브리스",
    "Barbacoa" to "바르바코아",
    "Barfi" to "바르피",
    "Barm cake" to "밤 케이크",
    "Barmbrack" to "밤브랙",
    "Basbousa" to "바스부사",
    "Basundi" to "바순디",
    "Bath bun" to "바스 번",
    "Bavarian cream" to "바바리안 크림",
    "Bazin" to "바진",
    "Bean pie" to "빈 파이",
    "Bear claw" to "베어 클로",
    "Beaten biscuit" to "비튼 비스킷",
    "Bedfordshire clanger" to "베드퍼드셔 클랜저",
    "Beef Manhattan" to "비프 맨해튼",
    "Beef Stroganoff" to "비프 스트로가노프",
    "Beef ball" to "소고기 완자",
    "Beef bourguignon" to "뵈프 부르기뇽",
    "Beef chow fun" to "비프 차우펀",
    "Beef noodle soup" to "우육면",
    "Beef on weck" to "비프 온 웩",
    "Beggar's Chicken" to "거지닭",
    "Beignet" to "베녜",
    "Bento" to "벤토",
    "Beondegi" to "번데기",
    "Berliner" to "베를리너",
    "Beshbarmak" to "베시바르막",
    "Bey's Soup" to "베이 수프",
    "Bhaji" to "바지",
    "Bhakri" to "바크리",
    "Biangbiang noodles" to "뱡뱡면",
    "Bibikkan" to "비비칸",
    "Bibimbap" to "비빔밥",
    "Bibingka" to "비빙카",
    "Bienenstich" to "비ienenstich",
    "Bife a cavalo" to "비페 아 카발로",
    "Bing" to "빙",
    "Bint al-sahn" to "빈트 알-산",
    "Bionico" to "비오니코",
    "Birria" to "비리아",
    "Biscuits and gravy" to "비스킷과 그레이비",
    "Bisque" to "비스크",
    "Bistek" to "비스텍",
    "Blaa" to "블라",
    "Black Forest gateau" to "블랙 포레스트 케이크",
    "Black and white cookie" to "흑백 쿠키",
    "Black bottom pie" to "블랙 바텀 파이",
    "Black pepper crab" to "블랙페퍼 크랩",
    "Black pudding" to "블랙 푸딩",
    "Black sesame soup" to "검은깨 수프",
    "Blackberry pie" to "블랙베리 파이",
    "Blodpalt" to "블로드팔트",
    "Blondie" to "블론디",
    "Blueberry pie" to "블루베리 파이",
    "Boat noodles" to "보트 누들",
    "Bob Andy pie" to "밥 앤디 파이",
    "Bob chorba" to "밥 초르바",
    "Boeber" to "보에버",
    "Boerewors" to "부르보스",
    "Bolani" to "볼라니",
    "Bolillo" to "볼리요",
    "Bolo de arroz" to "볼루 데 아로스",
    "Bolo de mel" to "볼루 데 멜",
    "Bolo do caco" to "볼루 두 카쿠",
    "Bologna sandwich" to "볼로냐 샌드위치",
    "Bologna sausage" to "볼로냐 소시지",
    "Bombay mix" to "봄베이 믹스",
    "Bon bon chicken" to "봉봉치킨",
    "Bonus Jack" to "보너스 잭",
    "Bookbinder soup" to "북바인더 수프",
    "Boondi" to "분디",
    "Boortsog" to "보르초크",
    "Booyah" to "부야",
    "Borlengo" to "보를렌고",
    "Borscht" to "보르시",
    "Bossam" to "보쌈",
    "Boston baked beans" to "보스턴 베이크드 빈스",
    "Boston cream doughnut" to "보스턴 크림 도넛",
    "Boston cream pie" to "보스턴 크림 파이",
    "Botifarra" to "보티파라",
    "Botok" to "보톡",
    "Boudin" to "부댕",
    "Bougatsa" to "부가차",
    "Bouillabaisse" to "부야베스",
    "Boxty" to "복스티",
    "Brandade" to "브랑다드",
    "Brandy snaps" to "브랜디 스냅",
    "Bratwurst" to "브라트부르스트",
    "Bread soup" to "빵 수프",
    "Breakfast burrito" to "브렉퍼스트 부리토",
    "Breakfast sandwich" to "브렉퍼스트 샌드위치",
    "Breakfast sausage" to "브렉퍼스트 소시지",
    "Brenebon" to "브레네본",
    "Bridie" to "브라이디",
    "Briouat" to "브리우아트",
    "Broa" to "브로아",
    "Brotzeit" to "브로차이트",
    "Brown Betty" to "브라운 베티",
    "Bruckfleisch" to "브룩플라이쉬",
    "Brunswick stew" to "브런즈윅 스튜",
    "Bryndzové halušky" to "브린조베 할루슈키",
    "Brændende kærlighed" to "브레넨데 케블리헤드",
    "Buchteln" to "부흐텔른",
    "Budae jjigae" to "부대찌개",
    "Buddha Jumps Over the Wall" to "불도장",
    "Buddha's delight" to "부처의 기쁨",
    "Buffalo burger" to "버팔로 버거",
    "Buffalo wing" to "버팔로 윙",
    "Bulgogi" to "불고기",
    "Bull roast" to "불 로스트",
    "Bundevara" to "분데바라",
    "Bundt cake" to "번트 케이크",
    "Bungeo-ppang" to "붕어빵",
    "Buntil" to "분틸",
    "Burgoo" to "버구",
    "Buridda" to "부리다",
    "Burkinabe cuisine" to "부르키나파소 요리",
    "Burmese tofu" to "버마 두부",
    "Burnt ends" to "번트 엔즈",
    "Burrito" to "부리토",
    "Butajiru" to "부타지루",
    "Butter chicken" to "버터 치킨",
    "Butter cookie" to "버터 쿠키",
    "Buttermilk koldskål" to "버터밀크 콜드스콜",
    "Buttermilk pie" to "버터밀크 파이",
    "Bánh bao" to "바인 바오",
    "Bánh bèo" to "바인 베오",
    "Bánh bột lọc" to "바인 봇 록",
    "Bánh canh" to "바인 칸",
    "Bánh chưng" to "바인 쯩",
    "Bánh cuốn" to "바인 꾸온",
    "Bánh xèo" to "반쎄오",
    "Bò 7 món" to "보 7몬",
    "Bò lúc lắc" to "보룩락",
    "Bò nướng lá lốt" to "보느엉라롯",
    "Börek" to "뵈렉",
    "Bún bò Huế" to "분보후에",
    "Bún riêu" to "분리에우",
    "Bún ốc" to "분옥",
    "Bündner Nusstorte" to "뷘트너 누스토르테",
    "Cabbage roll" to "양배추 롤",
    "Cabbage soup" to "양배추 수프",
    "Cabbie claw" to "캐비 클로",
    "Cabidela" to "카비델라",
    "Cabinet pudding" to "캐비닛 푸딩",
    "Cachupa" to "카추파",
    "Cacık" to "자즉",
    "Café liégeois" to "카페 리에주아",
    "Calas" to "칼라스",
    "Caldeirada" to "칼데이라다",
    "Caldillo de perro" to "칼디요 데 페로",
    "Caldo de pollo" to "칼도 데 포요",
    "Caldo de queso" to "칼도 데 케소",
    "Caldo de siete mares" to "칼도 데 시에테 마레스",
    "Caldo gallego" to "칼도 가예고",
    "Caldo tlalpeño" to "칼도 틀랄페뇨",
    "Calf's liver and bacon" to "송아지 간과 베이컨",
    "California-style pizza" to "캘리포니아 스타일 피자",
    "Calisson" to "칼리송",
    "Caltaboș" to "칼타보슈",
    "Calulu" to "칼룰루",
    "Candied almonds" to "설탕에 절인 아몬드",
    "Canjica" to "칸지카",
    "Cantonese seafood soup" to "광둥식 해산물 수프",
    "Caparrones" to "카파로네스",
    "Capirotada" to "카피로타다",
    "Caponata" to "카포나타",
    "Cappon magro" to "카폰 마그로",
    "Caprese salad" to "카프레제 샐러드",
    "Carac" to "카락",
    "Caramel" to "캐러멜",
    "Carbonade flamande" to "카르보나드 플라망드",
    "Carbonara" to "카르보나라",
    "Carciofi alla giudia" to "카르초피 알라 주디아",
    "Carne a la tampiqueña" to "카르네 아 라 탐피케냐",
    "Carne asada" to "카르네 아사다",
    "Carne asada fries" to "카르네 아사다 프라이",
    "Carne de porco à alentejana" to "카르네 데 포르코 아 알렌테자나",
    "Carne de vinha d'alhos" to "카르네 데 비냐 달료스",
    "Carne pizzaiola" to "카르네 피자이올라",
    "Carnitas" to "카르니타스",
    "Carrozza" to "카로차",
    "Cartellate" to "카르텔라테",
    "Caruru" to "카루루",
    "Casatiello" to "카사티엘로",
    "Cassoulet" to "카술레",
    "Castella" to "카스텔라",
    "Cawl" to "카울",
    "Cecina" to "세시나",
    "Celery Victor" to "셀러리 빅터",
    "Cemita" to "세미타",
    "Century egg" to "삭힌 오리알",
    "Ceviche" to "세비체",
    "Cha siu bao" to "차슈바오",
    "Chadachadi" to "차다차디",
    "Chahan" to "차항",
    "Chai tow kway" to "차이 토우 퀘이",
    "Chakalaka" to "차칼라카",
    "Chakapuli" to "차카풀리",
    "Chakhchoukha" to "착추카",
    "Chakodi" to "차코디",
    "Chaku" to "차쿠",
    "Challah" to "할라",
    "Chalupa" to "찰루파",
    "Champ" to "챔프",
    "Champon" to "짬뽕",
    "Champorado" to "참포라도",
    "Chana masala" to "차나 마살라",
    "Chanakhi" to "차나키",
    "Chanpurū" to "찬푸루",
    "Chantilly cake" to "샹티이 케이크",
    "Chao hong guo" to "차오 홍 궈",
    "Chapssal-tteok" to "찹쌀떡",
    "Char kway teow" to "차 퀘이 테오",
    "Char siu" to "차슈",
    "Charleston red rice" to "찰스턴 레드 라이스",
    "Chataamari" to "차타마리",
    "Chaudin" to "쇼댕",
    "Chawanmushi" to "자완무시",
    "Chazuke" to "자즈케",
    "Cheese dog" to "치즈 도그",
    "Cheese dream" to "치즈 드림",
    "Cheese fries" to "치즈 프라이",
    "Cheese sandwich" to "치즈 샌드위치",
    "Cheese straw" to "치즈 스트로",
    "Cheeseburger" to "치즈버거",
    "Cheesecake" to "치즈케이크",
    "Cheesesteak" to "치즈스테이크",
    "Chelsea bun" to "첼시 번",
    "Chermoula" to "체르물라",
    "Cherries jubilee" to "체리 주빌레",
    "Cherry kebab" to "체리 케밥",
    "Cherry pie" to "체리 파이",
    "Chess pie" to "체스 파이",
    "Chhena Jhili" to "체나 질리",
    "Chhena gaja" to "체나 가자",
    "Chhena jalebi" to "체나 잘레비",
    "Chhena kheeri" to "체나 키리",
    "Chhena poda" to "체나 포다",
    "Chicago-style hot dog" to "시카고 스타일 핫도그",
    "Chicago-style pizza" to "시카고 스타일 피자",
    "Chicken Divan" to "치킨 디반",
    "Chicken Française" to "치킨 프랑세즈",
    "Chicken Maryland" to "치킨 메릴랜드",
    "Chicken Vesuvio" to "치킨 베수비오",
    "Chicken and waffles" to "치킨과 와플",
    "Chicken bog" to "치킨 보그",
    "Chicken curry" to "치킨 커리",
    "Chicken fingers" to "치킨 핑거",
    "Chicken fried bacon" to "치킨 프라이드 베이컨",
    "Chicken fried steak" to "치킨 프라이드 스테이크",
    "Chicken karahi" to "치킨 카라히",
    "Chicken nugget" to "치킨 너겟",
    "Chicken paprikash" to "치킨 파프리카시",
    "Chicken riggies" to "치킨 리기스",
    "Chicken sandwich" to "치킨 샌드위치",
    "Chicken à la King" to "치킨 아 라 킹",
    "Chiffon pie" to "시폰 파이",
    "Chikhirtma" to "치히르트마",
    "Chikki" to "치키",
    "Chilaquiles" to "칠라킬레스",
    "Chile relleno" to "칠레 레예노",
    "Chili burger" to "칠리 버거",
    "Chili con carne" to "칠리 콘 카르네",
    "Chili dog" to "칠리 도그",
    "Chilli crab" to "칠리 크랩",
    "Chilorio" to "칠로리오",
    "Chim chum" to "침춤",
    "Chimichanga" to "치미창가",
    "Chinese noodles" to "중국 국수",
    "Chinese sausage" to "중국 소시지",
    "Chinese steamed eggs" to "중국식 계란찜",
    "Chips and dip" to "칩과 딥",
    "Chireta" to "치레타",
    "Chislic" to "치슬릭",
    "Chistorra" to "치스토라",
    "Chitranna" to "치트란나",
    "Choco pie" to "초코파이",
    "Chocolate brownie" to "초콜릿 브라우니",
    "Chocolate chip cookie" to "초콜릿 칩 쿠키",
    "Chocolate pudding" to "초콜릿 푸딩",
    "Chocolate-covered bacon" to "초콜릿 코팅 베이컨",
    "Chocolate-covered potato chips" to "초콜릿 코팅 감자칩",
    "Choila" to "초일라",
    "Chole bhature" to "촐레 바투레",
    "Chomchom" to "촘촘",
    "Chongos zamoranos" to "총고스 사모라노스",
    "Chorba" to "초르바",
    "Chorizo" to "초리소",
    "Chow mein" to "차우멘",
    "Chow mein sandwich" to "차우멘 샌드위치",
    "Chowder" to "차우더",
    "Chuchvara" to "추치바라",
    "Chueo-tang" to "추어탕",
    "Churchkhela" to "추르치헬라",
    "Churma" to "추르마",
    "Churrasco" to "추라스코",
    "Churro" to "추로",
    "Chwinamul" to "취나물",
    "Chè" to "체",
    "Chả giò" to "짜조",
    "Chả lụa" to "짜루아",
    "Ciabatta Bacon Cheeseburger" to "치아바타 베이컨 치즈버거",
    "Ciauscolo" to "치아우스콜로",
    "Ciccioli" to "치치올리",
    "Cifantuan" to "츠판퇀",
    "Cincalok" to "친찰록",
    "Cincinnati chili" to "신시내티 칠리",
    "Cinnamon roll" to "시나몬 롤",
    "Ciorbă" to "치오르버",
    "Ciorbă de perișoare" to "치오르버 데 페리쇼아레",
    "City chicken" to "시티 치킨",
    "Ciulama" to "치울라마",
    "Clafoutis" to "클라푸티",
    "Clam cake" to "클램 케이크",
    "Clam chowder" to "클램 차우더",
    "Clams casino" to "클램 카지노",
    "Claypot chicken rice" to "클레이팟 치킨 라이스",
    "Clootie" to "클루티",
    "Club sandwich" to "클럽 샌드위치",
    "Cobb salad" to "콥 샐러드",
    "Cobbler" to "코블러",
    "Coca" to "코카",
    "Cocada" to "코카다",
    "Cocada amarela" to "코카다 아마렐라",
    "Cochinita pibil" to "코치니타 피빌",
    "Cocido lebaniego" to "코시도 레바니에고",
    "Cocido madrileño" to "코시도 마드릴레뇨",
    "Cocido montañés" to "코시도 몬타녜스",
    "Cockle bread" to "코클 브레드",
    "Coconut bar" to "코코넛 바",
    "Coconut cake" to "코코넛 케이크",
    "Coconut rice" to "코코넛 라이스",
    "Colcannon" to "콜캐논",
    "Coleslaw" to "코울슬로",
    "Coney Island hot dog" to "코니 아일랜드 핫도그",
    "Cong you bing" to "총유빙",
    "Congee" to "콘지",
    "Consommé" to "콩소메",
    "Cookie salad" to "쿠키 샐러드",
    "Coq au vin" to "코코뱅",
    "Cordon bleu" to "코르동 블뢰",
    "Corn chowder" to "콘 차우더",
    "Corn cookie" to "옥수수 쿠키",
    "Corn crab soup" to "옥수수 게살 수프",
    "Corn dog" to "콘도그",
    "Corn pudding" to "콘 푸딩",
    "Corn relish" to "콘 렐리시",
    "Cornbread" to "콘브레드",
    "Cornish game hen" to "코니시 게임 헨",
    "Cornulețe" to "코르눌레체",
    "Corunda" to "코룬다",
    "Cottage Pudding" to "코티지 푸딩",
    "Cottage loaf" to "코티지 로프",
    "Coulibiac" to "쿨리비악",
    "Couque de Dinant" to "쿠크 드 디낭",
    "Couscous" to "쿠스쿠스",
    "Cowboy beans" to "카우보이 빈스",
    "Coyotas" to "코요타스",
    "Cozido à portuguesa" to "코지두 아 포르투게사",
    "Cozonac" to "코조낙",
    "Crab Louie" to "크랩 루이",
    "Crab cake" to "크랩 케이크",
    "Cranachan" to "크라나칸",
    "Crappit heid" to "크래핏 헤드",
    "Cream pie" to "크림 파이",
    "Creamed corn" to "크림드 콘",
    "Creamed eggs on toast" to "크림 달걀 토스트",
    "Crescentina modenese" to "크레센티나 모데네제",
    "Crispy fried chicken" to "크리스피 프라이드 치킨",
    "Cronut" to "크로넛",
    "Croquembouche" to "크로캉부슈",
    "Croquette" to "크로켓",
    "Crossing-the-bridge noodles" to "다리 건너는 국수",
    "Crème brûlée" to "크림 브륄레",
    "Crème caramel" to "크림 캐러멜",
    "Crêpe" to "크레이프",
    "Cuban sandwich" to "쿠바 샌드위치",
    "Cuchifritos" to "쿠치프리토스",
    "Cucumber soup" to "오이 수프",
    "Cudighi" to "쿠디기",
    "Cullen skink" to "컬렌 스킹크",
    "Cumian" to "추미엔",
    "Cupcake" to "컵케이크",
    "Curry bread" to "카레빵",
    "Curtido" to "쿠르티도",
    "Czernina" to "체르니나",
    "Cơm tấm" to "껌땀",
    "Dagwood sandwich" to "대그우드 샌드위치",
    "Daheen" to "다힌",
    "Dahi vada" to "다히 바다",
    "Dak-bokkeum-tang" to "닭볶음탕",
    "Dak-galbi" to "닭갈비",
    "Dakos" to "다코스",
    "Dal bhat" to "달밧",
    "Dal makhani" to "달 마카니",
    "Dampfnudel" to "담프누델",
    "Dandan noodles" to "탄탄면",
    "Dango" to "당고",
    "Dashi" to "다시",
    "Debrecener" to "데브레체너",
    "Delmonico steak" to "델모니코 스테이크",
    "Denver sandwich" to "덴버 샌드위치",
    "Derby pie" to "더비 파이",
    "Dessert bar" to "디저트 바",
    "Detroit-style pizza" to "디트로이트 스타일 피자",
    "Devil's food cake" to "데블스 푸드 케이크",
    "Deviled crab" to "데블드 크랩",
    "Deviled egg" to "데블드 에그",
    "Dhebra" to "데브라",
    "Dhindo" to "딘도",
    "Dhokla" to "도클라",
    "Dhondas" to "돈다스",
    "Dim sum" to "딤섬",
    "Dimlama" to "딤라마",
    "Diples" to "디플레스",
    "Dirt cake" to "더트 케이크",
    "Dirty macaroni" to "더티 마카로니",
    "Dirty rice" to "더티 라이스",
    "Doberge cake" to "도버지 케이크",
    "Dobos torte" to "도보스 토르테",
    "Dobradinha" to "도브라디냐",
    "Dodger Dog" to "다저 도그",
    "Dodo ikire" to "도도 이키레",
    "Doenjang-jjigae" to "된장찌개",
    "Dolma" to "돌마",
    "Dong'an chicken" to "동안 치킨",
    "Dongchimi" to "동치미",
    "Doodhpak" to "두드팍",
    "Double Down" to "더블 다운",
    "Double ka meetha" to "더블 카 미타",
    "Doughnut" to "도넛",
    "Douhua" to "더우화",
    "Douzhi" to "더우즈",
    "Dovga" to "도브가",
    "Draw soup" to "드로우 수프",
    "Dressed herring" to "드레스드 헤링",
    "Dripping cake" to "드리핑 케이크",
    "Drunken noodles" to "드렁큰 누들",
    "Duck blood and vermicelli soup" to "오리 피 당면 수프",
    "Duck rice" to "오리 쌀밥",
    "Dulce de leche" to "둘세 데 레체",
    "Dum Aloo" to "덤 알루",
    "Dumpling" to "만두",
    "Dyrlægens natmad" to "뒤를레겐스 나트마드",
    "Eba" to "에바",
    "Efo riro" to "에포 리로",
    "Egg drop soup" to "에그 드롭 수프",
    "Eggplant Salad" to "가지 샐러드",
    "Eggs Benedict" to "에그 베네딕트",
    "Eggs Neptune" to "에그 넵튠",
    "Eggs Sardou" to "에그 사르두",
    "Ekuru" to "에쿠루",
    "Elote" to "엘로테",
    "Ema datshi" to "에마 다치",
    "Empal gentong" to "엠팔 겐통",
    "Empanada" to "엠파나다",
    "Enchilada" to "엔칠라다",
    "Enduri Pitha" to "엔두리 피타",
    "Enne gai" to "엔네 가이",
    "Enormous Omelet Sandwich" to "거대한 오믈렛 샌드위치",
    "Entomatada" to "엔토마타다",
    "Erbazzone" to "에르바초네",
    "Erkuai" to "얼콰이",
    "Escalivada" to "에스칼리바다",
    "Escalope" to "에스칼로프",
    "Escargot" to "에스카르고",
    "Escudella i carn d'olla" to "에스쿠데야 이 카른 돌라",
    "Fabada asturiana" to "파바다 아스투리아나",
    "Flammekueche" to "플람퀴슈",
    "Flan" to "플란",
    "Flaouna" to "플라우나",
    "French dip" to "프렌치 딥",
    "Frogeye salad" to "프로그아이 샐러드",
    "Frozen banana" to "얼린 바나나",
    "Fuet" to "푸엣",
    "Gheimeh" to "게이메",
    "Greek salad" to "그릭 샐러드",
    "Green bean casserole" to "그린빈 캐서롤",
    "Gyeran-jjim" to "계란찜",
    "Gyeran-ppang" to "계란빵",
    "Hawaiian haystack" to "하와이안 헤이스택",
    "Hayashi rice" to "하야시라이스",
    "Hiyashi chūka" to "히야시추카",
    "Hoppang" to "호빵",
    "Isterband" to "이스터밴드",
    "Janchi-guksu" to "잔치국수",
    "Jiaozi" to "교자",
    "Kachumbari" to "카춤바리",
    "Kadhi" to "카디",
    "Kaeng khae" to "깽캐",
    "Kedgeree" to "케저리",
    "Kedjenou" to "케제누",
    "Khanom chan" to "카놈 찬",
    "Kibbeh" to "키베",
    "Kibinai" to "키비나이",
    "Kladdkaka" to "클라드카카",
    "Kosambari" to "코삼바리",
    "Kralan" to "크랄란",
    "Kulich" to "쿨리치",
    "Kuurdak" to "쿠르닥",
    "Kūčiukai" to "쿠츄카이",
    "Lablabi" to "라블라비",
    "Lai fun" to "라이펀",
    "Lapskaus" to "랍스카우스",
    "Laulau" to "라우라우",
    "Lebanon bologna" to "레바논 볼로냐",
    "Lecsó" to "레초",
    "Macaroni and cheese" to "마카로니 앤 치즈",
    "Magenbrot" to "마겐브로트",
    "Makdous" to "마크두스",
    "Meatball" to "미트볼",
    "Meeshay" to "미셰이",
    "Menudo" to "메누도",
    "Minestrone" to "미네스트로네",
    "Mititei" to "미티테이",
    "Mrouzia" to "므로지아",
    "Mămăligă" to "머멀리거",
    "Namul" to "나물",
    "Nan gyi thohk" to "난 기 톡",
    "Nanbanzuke" to "난반즈케",
    "Naryn" to "나린",
    "Neapolitan pizza" to "나폴리 피자",
    "Nopalito" to "노팔리토",
    "Oil noodles" to "오일 누들",
    "Okinawa soba" to "오키나와 소바",
    "Ostropel" to "오스트로펠",
    "Pan dulce" to "판 둘세",
    "Paska" to "파스카",
    "Pastry heart" to "페이스트리 하트",
    "Pasulj" to "파술",
    "Patatnik" to "파타트니크",
    "Pemmican" to "페미컨",
    "Pirog" to "피로그",
    "Plăcintă" to "플러친터",
    "Popara" to "포파라",
    "Potato salad" to "감자 샐러드",
    "Princess cake" to "프린세스 케이크",
    "Ras malai" to "라스 말라이",
    "Rasgulla" to "라스굴라",
    "Rolled oyster" to "롤드 오이스터",
    "Runeberg torte" to "루네베리 토르테",
    "Rösti" to "뢰슈티",
    "Rødgrød" to "뢰드그뢰드",
    "San-nakji" to "산낙지",
    "Scampi" to "스캄피",
    "Scotch broth" to "스코치 브로스",
    "Scotch pie" to "스코치 파이",
    "Scotcheroos" to "스코처루스",
    "Sea cucumber" to "해삼",
    "Sesame chicken" to "세사미 치킨",
    "Shahe fen" to "사허펀",
    "Shaker lemon pie" to "셰이커 레몬 파이",
    "Shanghai fried noodles" to "상하이 볶음면",
    "Shaobing" to "샤오빙",
    "Shark fin soup" to "샥스핀 수프",
    "Shchi" to "시치",
    "Shrikhand" to "슈리칸드",
    "Shrimp roe noodles" to "새우알 국수",
    "Skilandis" to "스킬란디스",
    "Skilpadjies" to "스킬파지스",
    "Sloppy joe" to "슬로피 조",
    "Sop saudara" to "솝 사우다라",
    "Sopa de Gato" to "소파 데 가토",
    "Sour cherry soup" to "사워 체리 수프",
    "Spiedie" to "스피디",
    "Struffoli" to "스트루폴리",
    "Sundubu-jjigae" to "순두부찌개",
    "Swiss roll" to "스위스 롤",
    "Tahu sumedang" to "타후 수메당",
    "Takikomi gohan" to "타키코미 고항",
    "Tarta de Santiago" to "타르타 데 산티아고",
    "Tarte Tatin" to "타르트 타탱",
    "Tekkadon" to "뎃카돈",
    "Thong yip" to "통입",
    "Tinginys" to "팅기니스",
    "Tongseng" to "통생",
    "Torta de gazpacho" to "토르타 데 가스파초",
    "Tsoureki" to "추레키",
    "Umeboshi" to "우메보시",
    "Vanillerostbraten" to "바닐레로스트브라텐",
    "Watergate salad" to "워터게이트 샐러드",
    "Whoopie pie" to "우피 파이",
    "Wodzionka" to "보지온카",
    "Yaksik" to "약식",
    "Yi mein" to "이몐"
    ,"Unagi" to "장어초밥"
    ,"Kimchi" to "김치"

)

/**
 * 영어 음식 이름을 받아 해당하는 한국어 이름을 반환하는 함수.
 * 만약 맵에 해당하는 한국어 이름이 없으면 원래의 영어 이름을 그대로 반환합니다.
 * @param englishName TFLite 모델에서 인식된 영어 레이블
 * @return 한국어 음식 이름 또는 원래 영어 이름
 */
fun getKoreanFoodName(englishName: String): String {
    return foodNameToKorean[englishName] ?: englishName
}